name: CI

on:
  push:
    branches:
      - develop-*
      - develop
      - master
  pull_request:
    branches:
      - develop-*
      - develop
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag tol-lab-share:black

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          tol-lab-share:black
          python -m black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag tol-lab-share:flake8

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          tol-lab-share:flake8
          flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag tol-lab-share:mypy

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          tol-lab-share:mypy
          python -m mypy .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nelonoel/branch-name@v1.0.1

      - name: Build and tag the image for testing and release
        run: >-
          docker build .
          --file Dockerfile
          --tag tol-lab-share:pytest

      - name: Run tests against the image
        run: >-
          docker run
          --entrypoint ''
          tol-lab-share:pytest
          python -m pytest -vx --cov=.

